export const ARTICLE_REMOVE = 'ARTICLE_REMOVE'
export const ARTICLE_LOAD_ALL = 'ARTICLE_LOAD_ALL'
export const ARTICLE_LOAD = 'ARTICLE_LOAD'

export const COMMENT_ADD = 'COMMENT_ADD'
export const FILTER_RANGE_SELECTION = 'FILTER_RANGE_SELECTION'
export const FILTER_RANGE_PERIOD = 'FILTER_RANGE_PERIOD'
export const INCREMENT = 'INCREMENT'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'