export const ARTICLE_REMOVE = 'ARTICLE_REMOVE'
export const ARTICLE_LOAD_ALL = 'ARTICLE_LOAD_ALL'

export const COMMENT_ADD = 'COMMENT_ADD'
export const FILTER_RANGE_SELECTION = 'FILTER_RANGE_SELECTION'
export const FILTER_RANGE_PERIOD = 'FILTER_RANGE_PERIOD'
export const INCREMENT = 'INCREMENT'